import routes from './routes';

const config = {
    routes,
    classicalCryptographyList: [
        { title: 'Ví dụ 1', to: routes.example1 },
        { title: 'Ví dụ 2', to: routes.example2 },
        { title: 'Mã hóa Caesar', to: routes.example2 },
    ],
    english: [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
    ],
    vietnamese: [
        'A',
        'Ă',
        'Â',
        'B',
        'C',
        'D',
        'Đ',
        'E',
        'Ê',
        'G',
        'H',
        'I',
        'K',
        'L',
        'M',
        'N',
        'O',
        'Ô',
        'Ơ',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'Ư',
        'V',
        'X',
        'Y',
    ],
    languageList: [
        {
            value: 'vietnamese',
            label: 'Tiếng Việt',
        },
        {
            value: 'english',
            label: 'Tiếng Anh',
        },
    ],
};

export default config;
